[build]
  base = "./"
  publish = "./dist/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NAME = "Anjali"
  NICKNAME = "Anjali"
  PIC = "Asset.png"
  HBD_MSG = "Happy Birthday, my love ❤️🎂"
  SCROLL_MSG = "birthday-message.txt"
